### ISSUE TITLE
R crashes on Mac with unexpanded path

### ISSUE THREAD

**Issue by thomasp85** [r-rust/gifski#6] opened 2018-08-29 15:45 UTC
If the output path is not expanded (e.g. '~/Desktop/animation.gif') my R session crashes when creating a gif

**Comment by jeroen** [comment] 2018-08-29 16:56
Duplicate of https://github.com/r-rust/gifski/issues/5

**Comment by jeroen** [comment] 2018-08-29 16:56
This should be fixed in the dev version>

**Closed by jeroen** 2018-08-29 16:56 UTC

**Comment by thomasp85** [comment] 2018-08-29 17:08
Oh - sorry for the noise
